      - name: Enviar correo
        if: env.NOTIFICAR == 'si'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.MAIL_APP_PASSWORD }}
          subject: Turismo Mujer cargó destinos
          to: tucorreo@ejemplo.com
          from: Monitor <cafaguarda@gmail.com>
          body: Revisa https://turismomujer.sernatur.cl/
